solution:
  created-for: cmsis-toobox@2.0.0

  cdefault:
  misc:
    - for-compiler: GCC
      C-CPP:
        - -ffunction-sections
        - -fdata-sections
      Link:
        - -Wl,--gc-sections

  packs:
    - pack: Microchip::SAMV71_DFP@4.10.230
    - pack: ARM::CMSIS@5.8.0
    - pack: ARM::CMSIS-FreeRTOS@11.1.0
    - pack: ARM::CMSIS-Driver@2.10.0
    - pack: ARM::CMSIS-View@1.2.0
    - pack: ARM::CMSIS-Compiler@2.1.0
    - pack: ARM::Cortex_DFP@1.1.0

solution:
  created-for: cmsis-toolbox@2.6  # CMSIS Toolbox version required
  cdefault:                       # Use default compiler settings from cdefault.yml
  compiler: GCC                   # Set compiler to GCC
  packs:                          # Required device pack
    - Atmel.SAMV71_DFP@1.0.0      # Replace with actual version installed
  target-types:                   # Specify target board
    - type: Board
      board: ATMEL::SAMV71-Xplained
  build-types:                    # Specify build types
    - type: Debug
      debug: on
    - type: Release
      optimize: size
  projects:                       # Include the blinky project
    - project: ./blinky/Blinky.cproject.yml

solution:
  name: BlinkyApp
  target:
    board: Microchip.SAMV71_XULT
    device: ATSAMV71Q21B
  packs:
    - ARM.CMSIS:5.9.0
    - Microchip.SAMV71_DFP:4.10.230
  layers:
    - BlinkyConfig
  toolchain: GCC
